#**Numpy Tutorial**

Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

While Python is slower in execution as compared to other languages like Fortran during looping, Numpy fastens Python’s operations by converting repetitive code to compiled form.

A Numpy Array is very similar to a Python list with a special condition that all of its elements must be of the same type.

In [ ]:
#Import Numpy Library
import numpy as np

##**1-Creating a Vector**

In [ ]:
#Load Library
import numpy as np

#Create a vector as a Row
vector_row = np.array([1,2,3])

#Create vector as a Column
vector_column = np.array([[1],[2],[3]])

# vector_row
vector_column

array([[1],
       [2],
       [3]])

##**2-Creating a Matrix**

We Create a 2-D Array in Numpy and call it a Matrix. It contains 2 rows and 3 columns.

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

# Find if a value exists in the array...Returns true if value exists else returns false
print(2 in matrix)

[[1 2 3]
 [4 5 6]]
True


In [ ]:
# Array of zeros
print(np.zeros(10))

# Array of ones with type int
print(np.ones(10, dtype=int))

# Range of numbers
rangeArray = np.array(range(10), int)
print(rangeArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[0 1 2 3 4 5 6 7 8 9]


##**3-Creating a Sparse Matrix**

Sparse Matrices store only non zero elements and assume all other values will be zero, leading to significant computational savings.

In [ ]:
#Load Library
import numpy as np
from scipy import sparse

#Create a Matrix
matrix = np.array([[0,0],[0,1],[3,0]])
print(matrix)

#Create Compressed Sparse Row(CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)
print(matrix_sparse)

[[0 0]
 [0 1]
 [3 0]]
  (1, 1)	1
  (2, 0)	3


##**4-Selecting Elements**

When you need to select one or more element in a vector or matrix

We can index the elements. Index in numpy array also starts with 0, so matrix[0] refers to the first element that is 1. We can also define a range such as [:2] which prints all values at indices 0 to 1. Creating such an array is highly useful because of its immense potential just like simply checking for an element in the array.


In [ ]:
#Load Library
import numpy as np

#Create a vector as a Row
vector_row = np.array([ 1,2,3,4,5,6 ])

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Select 3rd element of Vector
print(vector_row[2])

#Select 2nd row 2nd column
print(matrix[1,1])

#Select all elements of a vector
print(vector_row[:])

#Select everything up to and including the 3rd element
print(vector_row[:3])

#Select the everything after the 3rd element
print(vector_row[3:])

#Select the last element
print(vector_row[-1])

#Select the first 2 rows and all the columns of the matrix
print(matrix[:2,:])

#Select all rows and the 2nd column of the matrix
print(matrix[:,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
5
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6
[[1 2 3]
 [4 5 6]]
[[2]
 [5]
 [8]]


In [ ]:
#Selects all rows from row0 onwards and all columns from column1 onwards
arr2=arr1[0:,1:]
arr2

array([[2, 3],
       [5, 6]])

In [ ]:
# Select the 2nd Row & 3rd Column Value
matrix[1][2]

6

##**5-Describing a Matrix**

When you want to know about the shape size and dimensions of a Matrix.

In [ ]:
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

#View the Number of Rows and Columns
print(matrix.shape)

#View the number of elements (rows*columns)
print(matrix.size)

#View the number of Dimensions(2 in this case)
print(matrix.ndim)

(3, 3)
9
2


##**6-Operations to Elements**

You want to apply some function to multiple elements in an array.
Numpy’s vectorize class converts a function into a function that can apply to multiple elements in an array or slice of an array.

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Create a function that adds 100 to something
add_100 =lambda i: i+100

#Convert it into a vectorized function
vectorized_add_100= np.vectorize(add_100)

#Apply function to all elements in matrix
print(vectorized_add_100(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[101 102 103]
 [104 105 106]
 [107 108 109]]


##**7-Max & Min values**

We use Numpy’s max and min functions

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Return the max element
print(np.max(matrix))

#Return the min element
print(np.min(matrix))

#To find the max element in each column
print(np.max(matrix,axis=0))

#To find the max element in each row
print(np.max(matrix,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
1
[7 8 9]
[3 6 9]


##**8-Calc Avg, Var & Std Dev**

When you want to calculate some descriptive statistics about an array

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Mean
print(np.mean(matrix))

#Standard Dev.
print(np.std(matrix))

#Variance
print(np.var(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5.0
2.581988897471611
6.666666666666667


##**9-Reshaping Arrays**

When you want to reshape an array(changing the number of rows and columns) without changing the elements.

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Reshape
print(matrix.reshape(9,1))

#Here -1 says as many columns as needed and 1 row
print(matrix.reshape(1,-1))

#If we provide only 1 value Reshape would return a 1-d array of that length
print(matrix.reshape(9))

#We can also use the Flatten method to convert a matrix to 1-d array
print(matrix.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


##**10-Transposing**

By transposing you interchange the rows and columns of a Matrix

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Transpose the matrix
print(matrix.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


##**11-Determinant & Rank**

The rank of a Matrix is the number of dimensions of the vector space spanned by its rows or columns

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Calculate the Determinant
print(np.linalg.det(matrix))

#Calculate the Rank
print(np.linalg.matrix_rank(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0
2


##**12-Diagonal**

When you need to extract only the diagonal elements of a matrix

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Print the Principal diagonal
print(matrix.diagonal())

#Print the diagonal one above the Principal diagonal
print(matrix.diagonal(offset=1))

#Print the diagonal one below Principal diagonal
print(matrix.diagonal(offset=-1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
[2 6]
[4 8]


##**13-Trace**

Trace of a Matrix is the sum of elements on the Principal Diagonal of the Matrix.

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Print the Trace
print(matrix.trace())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


##**14-Eigenvalues & Eigenvectors**

Eigenvectors are widely used in Machine Learning libraries. Intutively given a linear transformation represented by a matrix,A, eigenvectors are vectors that when that transformation is applied, change only in scale(not direction).More formally
Av=Kv

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

# Calculate the Eigenvalues and Eigenvectors of that Matrix
eigenvalues ,eigenvectors=np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


##**15-Dot & Cross Products**

In [ ]:
#Load Library
import numpy as np

#Create vector-1
vector_1 = np.array([ 1,2,3 ])
#Create vector-2
vector_2 = np.array([ 4,5,6 ])

#Calculate Dot Product
print("Dot Product:",np.dot(vector_1,vector_2))

#Alternatively you can use @ to calculate dot products
print("Dot Product using @:",vector_1 @ vector_2)

# Cross operator
print("Cross Product:",np.cross(vector_1,vector_2))

Dot Product: 32
Dot Product using @: 32
Cross Product: [-3  6 -3]


##**16-Add, Subtract, Multiply, Sort, nUnique**

Numpy overloads all basic functions so that they can operate on arrays for example the plus operator +, multiply operator * etc. are all overloaded for arrays. Special functions such as square root and log are also available. These operations occur element-wise, thus when interacting with multiple arrays, they must all have same shape. There are many other operations possible such as exp, sin, cos, tan, and abs. We can also sort(), find min() and max(), determine unique() values, diagonal() elements of a matrix and sort() elements. If we add arg in front of min or max, we can also get the index of the minimum or maximum value in the array.

In [ ]:
#Load Library
import numpy as np

#Create Matrix
matrix_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_2 = np.array([[7,8,9],[4,5,6],[1,2,3]])

#Add the 2 Matrices
print(np.add(matrix_1,matrix_2))

#Subtraction
print(np.subtract(matrix_1,matrix_2))

#Multiplication(Element wise, not Dot Product)
print(matrix_1*matrix_2)

# Get unqiue values
print(f"Unique values: {np.unique(matrix_1)}")

# Sort values in the multidimensional array
print(f"Sorted:{np.sort(matrix_1)}")

[[ 8 10 12]
 [ 8 10 12]
 [ 8 10 12]]
[[-6 -6 -6]
 [ 0  0  0]
 [ 6  6  6]]
[[ 7 16 27]
 [16 25 36]
 [ 7 16 27]]
Unique values: [1 2 3 4 5 6 7 8 9]
Sorted:[[1 2 3]
 [4 5 6]
 [7 8 9]]


##**ArgPartition, Allclose, Clip, Extract, Where, Percentile**

* NumPy has this amazing function which can find N largest values index. The output will be the N largest values index, and then we can sort the values if needed.

* Allclose() is used for matching two arrays and getting the output in terms of a boolean value. It will return False if items in two arrays are not equal within a tolerance. It is a great way to check if two arrays are similar, which can actually be difficult to implement manually.

* Clip() is used to keep values in an array within an interval. Sometimes, we need to keep the values within an upper and lower limit. For the mentioned purpose, we can make use of NumPy’s clip(). Given an interval, values outside the interval are clipped to the interval edges.

* Extract() as the name goes, is used to extract specific elements from an array based on a certain condition. With extract(), we can also use conditions like and and or.

* Where() is used to return elements from an array that satisfy a certain condition. It returns the index position of values that fall in a certain condition. This is almost similar to the where condition that we use in SQL

* Percentile() is used to compute the nth percentile of the array elements along the specified axis.

In [ ]:
# Argpartition 
x = np.array([12, 10, 12, 0, 6, 8, 9, 1, 16, 4, 6, 0])
index_val = np.argpartition(x, -4)[-4:]

np.sort(x[index_val])

array([10, 12, 12, 16])

In [ ]:
# AllClose
array1 = np.array([0.12,0.17,0.24,0.29])
array2 = np.array([0.13,0.19,0.26,0.31])

# with a tolerance of 0.1, it should return False:
print(np.allclose(array1,array2,0.1))

# with a tolerance of 0.2, it should return True:
print(np.allclose(array1,array2,0.2))

False
True


In [ ]:
# Clip
x = np.array([3, 17, 14, 23, 2, 2, 6, 8, 1, 2, 16, 0])
np.clip(x,2,5)

array([3, 5, 5, 5, 2, 2, 5, 5, 2, 2, 5, 2])

In [ ]:
# Apply condition on extract directly
array = np.random.randint(20, size=12)
np.extract(((array < 3) | (array > 15)), array)

array([17, 16, 19, 18,  0])

In [ ]:
# Where
y = np.array([1,5,6,8,1,7,3,6,9])

# First will replace the values that match the condition, 
# second will replace the values that does not
np.where(y>5, "Hit", "Miss")

array(['Miss', 'Miss', 'Hit', 'Hit', 'Miss', 'Hit', 'Miss', 'Hit', 'Hit'],
      dtype='<U4')

In [ ]:
# Percentile

#50th Percentile of a, axis = 0 :  6.0
a = np.array([1,5,6,8,1,7,3,6,9])
print("50th Percentile of a, axis = 0 : ",np.percentile(a, 50, axis =0))

#30th Percentile of b, axis = 0
b = np.array([[10, 7, 4], [3, 2, 1]])
print("30th Percentile of b, axis = 0 : ", np.percentile(b, 30, axis =0))

50th Percentile of a, axis = 0 :  6.0
30th Percentile of b, axis = 0 :  [5.1 3.5 1.9]


##**18-Inverse**

This is used when you want to calculate the inverse of a Square Matrix

In [ ]:
#Load Library
import numpy as np

#Create a Matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#Calculate its inverse
print(np.linalg.inv(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


LinAlgError: ignored

##**19-Random values**

It can sometimes be useful to return the same random numbers to get predictable, repeatable results. We can do so by setting the ‘Seed’ (An Integer) of the pseudorandom generator. Random processes with the same seed would always produce the same result.

np.random enables us to define the random arrays. The function rand() defines a random array if the argument includes a single integer e.g. 5 in the example above and a random matrix if the argument is a combination of integers e.g. (5,4) in the matrix example above. This function returns value within the range of 0 to 1 but if we want integers we should instead use randint(). It takes the first argument as start value, second argument as end value and the third argument as the shape of the array.

In [ ]:
print(np.random.rand(5))

[0.53881673 0.41919451 0.6852195  0.20445225 0.87811744]


In [ ]:
print(np.random.rand(5,4))

[[0.02738759 0.67046751 0.4173048  0.55868983]
 [0.14038694 0.19810149 0.80074457 0.96826158]
 [0.31342418 0.69232262 0.87638915 0.89460666]
 [0.08504421 0.03905478 0.16983042 0.8781425 ]
 [0.09834683 0.42110763 0.95788953 0.53316528]]


In [ ]:
#Creates a random normal distribution
np.random.randn(4,2)

array([[-1.65451545, -0.4829414 ],
       [-1.80662901, -0.91544761],
       [-0.06973398, -0.84995477],
       [ 0.05062323,  0.70507238]])

In [ ]:
#Selects 10 numbers between 0 & 100
np.random.randint(0,100,10) 

array([87, 25, 71, 92, 74, 62, 46, 32, 88, 23])

In [ ]:
#Gives 50 equally spaced points between 0 & 10
arr1=np.linspace(0,10,50)
arr1

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

##**20-Concatenate**

In [ ]:
# Concatenation of multi-dimensional arrays
arr1 = np.array([[1,2], [3,4]], int)
arr2 = np.array([[5,6], [7,8]], int)
print(np.concatenate((arr1, arr2)))

# Based Row
print(np.concatenate((arr1, arr2), axis=0))

# Based on Column
print(np.concatenate((arr1, arr2), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


##**21-BroadCasting**

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [ ]:
#Broadcasting
arr[3:]=100
arr

array([  0. ,   0.5,   1. , 100. , 100. , 100. , 100. , 100. , 100. ,
       100. , 100. , 100. , 100. , 100. , 100. , 100. , 100. , 100. ,
       100. , 100. ])